name: Cross Platform Check
on: [push, pull_request]

jobs:
  check:
    runs-on: docker
    container:
      image: rust:latest
    steps:
      - name: test
        uses: actions/checkout@v4

      - name: run test
        run: |
          cargo check
          cargo test